export const AUTH_TOKEN = 'auth_token'
export const AUTH_USER = 'auth_user'
export const BUILDINGS_ITEMS_PER_PAGE = 'BUILDINGS_ITEMS_PER_PAGE'
export const LANDS_ITEMS_PER_PAGE = 'lands_items_per_page'
export const BUILDING_CONTACTS_ITEMS_PER_PAGE = 'BUILDING_CONTACTS_ITEMS_PER_PAGE'
export const USERS_ITEMS_PER_PAGE = 'users_items_per_page'
export const ITEMS_PER_PAGE = 'items_per_page'
export const CAMS_ITEMS_PER_PAGE = 'cams_items_per_page'
