import httpClient from '../../plugins/axios'

export default {
  getAbsorptionBuildings(buildingId, query, filters = {}, sorter = {}) {
    return httpClient.get(`/buildings/${buildingId}/absorption`, {
      params: {
        page: query?.page || null,
        size: query?.size || null,
        search: query?.search || null,
        ...filters,
        ...sorter,
      },
    })
  },
  getAbsorptionBuilding(buildingAbsoprtionId, buildingId) {
    return httpClient.get(`/buildings/${buildingId}/absorption/${buildingAbsoprtionId}`)
  },
  createAbsorptionBuilding(
    buildingId,
    {
      building_id,
      dock_doors,
      abs_tenant_id,
      abs_industry_id,
      abs_country_id,
      broker_id,
      shared_truck,
      new_construction,
      is_starting_construction,
      bay_size,
      columns_spacing,
      abs_lease_term_month,
      parking_space,
      abs_closing_rate,
      abs_closing_date,
      abs_lease_up,
      abs_month,
      abs_sale_price,
      abs_type,
      abs_final_use,
      abs_company_type,
      offices_space_sf,
      ramps,
      avl_date,
      abs_min_lease,
      abs_max_lease,
      truck_court_ft,
      size_sf,
      trailer_parking_space,
      fire_protection_system,
      above_market_tis,
      abs_deal,
      abs_shelter_id,
      sqftToM2,
    },
  ) {
    return httpClient.post(`/buildings/${buildingId}/absorption`, {
      building_id,
      dock_doors,
      abs_tenant_id,
      abs_industry_id,
      abs_country_id,
      broker_id,
      shared_truck,
      new_construction,
      is_starting_construction,
      bay_size,
      columns_spacing,
      abs_lease_term_month,
      parking_space,
      abs_closing_rate,
      abs_closing_date,
      abs_lease_up,
      abs_month,
      abs_sale_price,
      abs_type,
      abs_final_use,
      abs_company_type,
      offices_space_sf,
      ramps,
      avl_date,
      abs_min_lease,
      abs_max_lease,
      truck_court_ft,
      size_sf,
      trailer_parking_space,
      fire_protection_system,
      above_market_tis,
      abs_deal,
      abs_shelter_id,
      sqftToM2,
    })
  },
  updateAbsorptionBuilding(
    buildingAbsoprtionId,
    buildingId,
    {
      building_id,
      dock_doors,
      abs_tenant_id,
      abs_industry_id,
      abs_country_id,
      broker_id,
      shared_truck,
      new_construction,
      is_starting_construction,
      bay_size,
      columns_spacing,
      abs_lease_term_month,
      parking_space,
      abs_closing_rate,
      abs_closing_date,
      abs_lease_up,
      abs_month,
      abs_sale_price,
      abs_type,
      abs_final_use,
      abs_company_type,
      offices_space_sf,
      ramps,
      truck_court_ft,
      size_sf,
      trailer_parking_space,
      fire_protection_system,
      above_market_tis,
      abs_deal,
      abs_shelter_id,
      sqftToM2,
    },
  ) {
    return httpClient.put(`/buildings/${buildingId}/absorption/${buildingAbsoprtionId}`, {
      building_id,
      dock_doors,
      abs_tenant_id,
      abs_industry_id,
      abs_country_id,
      broker_id,
      shared_truck,
      new_construction,
      is_starting_construction,
      bay_size,
      columns_spacing,
      abs_lease_term_month,
      parking_space,
      abs_closing_rate,
      abs_closing_date,
      abs_lease_up,
      abs_month,
      abs_sale_price,
      abs_type,
      abs_final_use,
      abs_company_type,
      offices_space_sf,
      ramps,
      truck_court_ft,
      size_sf,
      trailer_parking_space,
      fire_protection_system,
      above_market_tis,
      abs_deal,
      abs_shelter_id,
      sqftToM2,
    })
  },
  deleteAbsorptionBuilding(buildingAbsoprtionId, buildingId) {
    return httpClient.delete(`/buildings/${buildingId}/absorption/${buildingAbsoprtionId}`)
  },
}
