export const ROUTE_NAMES = {
  LOGIN: 'Login',
  HOME: 'Home',
  DASHBOARD: 'Dashboard',
  OPERATIONS: 'Operation',
  BUILDINGS: 'Market Size',
  BUILDINGS_CREATE: 'Create Market Size',
  BUILDINGS_UPDATE: 'Edit Market Size',
  USERS: 'Users',
  USERS_CREATE: 'Create User',
  USERS_UPDATE: 'Update User',
  USERS_DETAIL: 'User Detail',
  DEVELOPERS: 'Developers',
  DEVELOPERS_CREATE: 'Create Developer',
  DEVELOPERS_UPDATE: 'Edit Developer',
  ROLES: 'Roles',
  ROLES_CREATE: 'Create Role',
  ROLES_UPDATE: 'Update Role',
  INDUSTRIAL_PARKS: 'Industrial Parks',
  INDUSTRIAL_PARKS_DETAIL: 'Industrial Park Detail',
  COMPANIES_INDEX: 'Companies',
  COMPANIES_CREATE: 'Create Company',
  COMPANIES_UPDATE: 'Edit Company',
  COMPANY_DETAIL: 'Company Detail',
  SECURITY: 'Security',
  POLICIES: 'Policies',
  POLICY_DETAIL: 'Policy Detail',
  INDUSTRIES: 'Industries',
  BROKERS_INDEX: 'Brokers',
  BROKERS_CREATE: 'Create Broker',
  BROKERS_UPDATE: 'Edit Broker',
  INDUSTRY_CREATE: 'Industry Create',
  INDUSTRY_UPDATE: 'Industry Update',
  REITS: 'REITs',
  REITS_CREATE: 'Create REIT',
  REITS_UPDATE: 'Edit REIT',

  LANDS_INDEX: 'Lands',
  LANDS_CREATE: 'Create Lands',
  LANDS_UPDATE: 'Edit Lands',

  TENANTS_INDEX: 'Tenants',
  TENANTS_DETAIL: 'Tenant Detail',

  MARKET_SIZE_PENDING_APPROVALS: 'Pending Approvals',
  CATALOGS: 'Catalogs',

  REITS_INDEX: 'Reits',

  REIT_MORTGAGE: 'Reit Mortgage',
  REIT_MORTGAGE_CREATE: 'Create Reit Mortgage',
  REIT_MORTGAGE_UPDATE: 'Edit Reit Mortgage',



  REIT_ANNUAL_INDEX: 'REIT Annual',
  REIT_ANNUAL_CREATE: 'Create REIT Annual',
  REIT_ANNUAL_UPDATE: 'Update REIT Annual',

  REIT_QUARTER_INDEX: 'REIT Quarter',
  REIT_QUARTER_CREATE: 'Create REIT Quarter',
  REIT_QUARTER_UPDATE: 'Update REIT Quarter',
}
