export const ROUTE_NAMES = {
  LOGIN: 'Login',
  HOME: 'home',
  DASHBOARD: 'dashboard',
  OPERATIONS: 'Operacion',
  BUILDINGS: 'Buildings',
  BUILDINGS_CREATE: 'Create Buildings',
  BUILDINGS_UPDATE: 'Edit Buildings',
  USERS: 'Users',
  USERS_CREATE: 'CreateUser',
  USERS_UPDATE: 'UpdateUser',
  DEVELOPERS: 'Developers',
  DEVELOPERS_CREATE: 'Create Developer',
  DEVELOPERS_UPDATE: 'Edit Developer',
  INDUSTRIAL_PARKS: 'Industrial Parks',
  INDUSTRIAL_PARKS_DETAIL: 'Industrial Park Detail',
  COMPANIES: 'Companies',
  COMPANY_DETAIL: 'CompanyDetail',
  SECURITY: 'Security',
  POLICIES: 'Policies',
  POLICY_DETAIL: 'PolicyDetail',
  INDUSTRIES: 'Industries',
  INDUSTRY_CREATE: 'IndustryCreate',
  INDUSTRY_UPDATE: 'IndustryUpdate',

  LANDS_INDEX: 'Lands',
  LANDS_CREATE: 'Create Lands',
  LANDS_UPDATE: 'Edit Lands',
}
