export const ROUTE_NAMES = {
  LOGIN: 'Login',
  HOME: 'home',
  DASHBOARD: 'dashboard',
  OPERATIONS: 'Operacion',
  BUILDINGS: 'Market Size',
  BUILDINGS_CREATE: 'Create Market Size',
  BUILDINGS_UPDATE: 'Edit Market Size',
  USERS: 'Users',
  USERS_CREATE: 'CreateUser',
  USERS_UPDATE: 'UpdateUser',
  DEVELOPERS: 'Developers',
  DEVELOPERS_CREATE: 'Create Developer',
  DEVELOPERS_UPDATE: 'Edit Developer',
}
